# Generated by Django 5.2 on 2026-02-19 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('seller_account', models.CharField(blank=True, max_length=100)),
                ('marketplace', models.CharField(default='Amazon', max_length=50)),
                ('country', models.CharField(default='US', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brands',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Closure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('closure_type', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'closures',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_key', models.SlugField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('decimal', 'Decimal'), ('date', 'Date'), ('boolean', 'Yes/No'), ('select', 'Dropdown'), ('multiselect', 'Multi-Select'), ('url', 'URL')], default='text', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('reference_table', models.CharField(blank=True, max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('show_in_list', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_field_definitions',
                'ordering': ['display_order', 'name'],
                'unique_together': {('user', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='DOISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('amazon_doi_goal', models.IntegerField(default=93)),
                ('inbound_lead_time', models.IntegerField(default=30)),
                ('manufacture_lead_time', models.IntegerField(default=7)),
                ('market_adjustment', models.FloatField(default=0.05)),
                ('velocity_weight', models.FloatField(default=0.15)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doi_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doi_settings',
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('npk', models.CharField(blank=True, max_length=50)),
                ('guaranteed_analysis', models.TextField(blank=True)),
                ('derived_from', models.TextField(blank=True)),
                ('storage_warranty', models.TextField(blank=True)),
                ('filter_type', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'formulas',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('packaging_type', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('label_size', models.CharField(blank=True, max_length=100)),
                ('case_size', models.CharField(blank=True, max_length=100)),
                ('units_per_case', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'packaging_types',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(blank=True, db_index=True, max_length=20)),
                ('parent_asin', models.CharField(blank=True, max_length=20)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100)),
                ('upc', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('product_type', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('launched', 'Launched'), ('pending', 'Pending'), ('discontinued', 'Discontinued'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('is_hazmat', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='forecast_app.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ForecastCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_version', models.CharField(default='v1', max_length=20)),
                ('forecast_date', models.DateField()),
                ('units_to_make', models.IntegerField(default=0)),
                ('current_doi', models.FloatField(default=0)),
                ('runout_date', models.DateField(blank=True, null=True)),
                ('cumulative_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('critical', 'Critical'), ('low', 'Low Stock'), ('good', 'Good'), ('overstock', 'Overstock')], default='good', max_length=20)),
                ('calculation_time', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='forecast_app.product')),
            ],
            options={
                'db_table': 'forecast_cache',
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_reference_id', models.IntegerField(blank=True, null=True)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast_app.customfielddefinition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='forecast_app.product')),
            ],
            options={
                'db_table': 'custom_field_values',
            },
        ),
        migrations.CreateModel(
            name='ProductExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_location', models.CharField(blank=True, max_length=100)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('core_competitor_asins', models.TextField(blank=True)),
                ('other_competitor_asins', models.TextField(blank=True)),
                ('core_keywords', models.TextField(blank=True)),
                ('other_keywords', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_title', models.CharField(blank=True, max_length=500)),
                ('bullets', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('vine_launch_date', models.DateField(blank=True, null=True)),
                ('vine_units_enrolled', models.IntegerField(blank=True, null=True)),
                ('vine_reviews', models.IntegerField(blank=True, null=True)),
                ('star_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('notes', models.TextField(blank=True)),
                ('closure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecast_app.closure')),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecast_app.formula')),
                ('formula_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_formula2', to='forecast_app.formula')),
                ('packaging', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecast_app.packagingtype')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended', to='forecast_app.product')),
            ],
            options={
                'db_table': 'products_extended',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'asin'], name='products_user_id_852a12_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'sku'], name='products_user_id_4299ac_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'status'], name='products_user_id_04266d_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastcache',
            index=models.Index(fields=['product', 'forecast_date'], name='forecast_ca_product_4618ea_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastcache',
            index=models.Index(fields=['status'], name='forecast_ca_status_3b53d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forecastcache',
            unique_together={('product', 'algorithm_version', 'forecast_date')},
        ),
        migrations.AlterUniqueTogether(
            name='customfieldvalue',
            unique_together={('product', 'field_definition')},
        ),
    ]
