# Generated by Django 5.2 on 2026-02-19 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'is_active', 'status'], name='products_user_id_b0db6e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'brand', '-created_at'], name='products_user_id_bb26b7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', '-created_at'], name='products_user_id_c61fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_name_6f9890_idx'),
        ),
    ]
