# Generated by Django 5.0.1 on 2026-02-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0002_add_product_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productextended',
            name='case_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Case height in inches', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productextended',
            name='case_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Case length in inches', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productextended',
            name='case_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Case weight in lbs', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='productextended',
            name='case_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Case width in inches', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productextended',
            name='units_per_case',
            field=models.IntegerField(blank=True, help_text='Number of units per case', null=True),
        ),
    ]
