# Generated by Django 5.0.1 on 2026-02-25 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_integration', '0001_initial'),
        ('forecast_app', '0003_add_case_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_account',
            field=models.ForeignKey(blank=True, help_text='The Amazon seller account this product belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='amazon_integration.amazonselleraccount'),
        ),
    ]
