# Generated by Django 5.0.1 on 2026-03-12 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0004_product_amazon_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bottle Name - primary identifier', max_length=200)),
                ('image', models.URLField(blank=True, help_text='Bottle Image URL', max_length=500)),
                ('size_oz', models.DecimalField(blank=True, decimal_places=2, help_text='Size in oz', max_digits=8, null=True)),
                ('shape', models.CharField(blank=True, help_text='e.g., Tall Cylinder, Standard Handle, Rounded', max_length=100)),
                ('color', models.CharField(blank=True, help_text='e.g., White, Clear', max_length=50)),
                ('thread_type', models.CharField(blank=True, help_text='e.g., Non-Ratchet, Ratchet', max_length=50)),
                ('cap_size', models.CharField(blank=True, help_text='e.g., 38-400, 24-410, 28-410', max_length=50)),
                ('material', models.CharField(blank=True, help_text='e.g., HDPE, PET, PETE', max_length=50)),
                ('supplier', models.CharField(blank=True, help_text='Supplier name', max_length=200)),
                ('packaging_part_number', models.CharField(blank=True, help_text='Supplier part number', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Full supplier description')),
                ('brand', models.CharField(blank=True, help_text='Brand/manufacturer', max_length=200)),
                ('lead_time_weeks', models.IntegerField(blank=True, help_text='Lead time in weeks', null=True)),
                ('moq', models.IntegerField(blank=True, help_text='Minimum Order Quantity', null=True)),
                ('units_per_pallet', models.IntegerField(blank=True, null=True)),
                ('units_per_case', models.IntegerField(blank=True, null=True)),
                ('cases_per_pallet', models.IntegerField(blank=True, null=True)),
                ('box_size', models.CharField(blank=True, help_text='e.g., 12x10x12', max_length=50)),
                ('box_length_in', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('box_width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('box_height_in', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('units_per_case_finished', models.IntegerField(blank=True, help_text='Units per case (finished goods)', null=True)),
                ('units_per_gallon', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('box_weight_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_boxes_per_pallet', models.IntegerField(blank=True, null=True)),
                ('single_box_pallet_share', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('replenishment_strategy', models.CharField(blank=True, choices=[('corral', 'Corral'), ('manual', 'Manual'), ('auto', 'Auto')], max_length=20)),
                ('packaging_bpm', models.IntegerField(blank=True, help_text='Bottles per minute', null=True)),
                ('length_in', models.DecimalField(blank=True, decimal_places=2, help_text='Product length in inches', max_digits=6, null=True)),
                ('width_in', models.DecimalField(blank=True, decimal_places=2, help_text='Product width in inches', max_digits=6, null=True)),
                ('height_in', models.DecimalField(blank=True, decimal_places=2, help_text='Product height in inches', max_digits=6, null=True)),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=2, help_text='Product weight in lbs', max_digits=8, null=True)),
                ('label_size', models.CharField(blank=True, help_text='e.g., 5" x 8"', max_length=50)),
                ('supplier_order_strategy', models.CharField(blank=True, choices=[('manual', 'Manual'), ('auto', 'Auto')], max_length=20)),
                ('supplier_inventory', models.IntegerField(blank=True, null=True)),
                ('warehouse_inventory', models.IntegerField(blank=True, null=True)),
                ('max_warehouse_inventory', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bottles',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='closure',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='closure',
            name='closure_type',
        ),
        migrations.AddField(
            model_name='closure',
            name='brand',
            field=models.CharField(blank=True, help_text='e.g., Berry, Aptar', max_length=200),
        ),
        migrations.AddField(
            model_name='closure',
            name='cap_size',
            field=models.CharField(blank=True, help_text='e.g., 38-400, 24-410, 28-410', max_length=50),
        ),
        migrations.AddField(
            model_name='closure',
            name='cases_per_pallet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='closure',
            name='category',
            field=models.CharField(choices=[('closure', 'Closure'), ('cap', 'Cap'), ('sprayer', 'Sprayer'), ('pump', 'Pump')], default='closure', max_length=50),
        ),
        migrations.AddField(
            model_name='closure',
            name='color',
            field=models.CharField(blank=True, help_text='e.g., White, Clear', max_length=50),
        ),
        migrations.AddField(
            model_name='closure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='closure',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='closure',
            name='image',
            field=models.URLField(blank=True, help_text='Closure Image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='closure',
            name='lead_time_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='closure',
            name='material',
            field=models.CharField(blank=True, help_text='e.g., P/P', max_length=50),
        ),
        migrations.AddField(
            model_name='closure',
            name='max_warehouse_inventory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='closure',
            name='moq',
            field=models.IntegerField(blank=True, help_text='Minimum Order Quantity', null=True),
        ),
        migrations.AddField(
            model_name='closure',
            name='packaging_part_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='closure',
            name='shape',
            field=models.CharField(blank=True, help_text='e.g., Standard, Pour Top, Top Down, Trigger', max_length=100),
        ),
        migrations.AddField(
            model_name='closure',
            name='supplier',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='closure',
            name='supplier_inventory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='closure',
            name='supplier_order_strategy',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('auto', 'Auto')], max_length=20),
        ),
        migrations.AddField(
            model_name='closure',
            name='thread_type',
            field=models.CharField(blank=True, help_text='e.g., Non-Ratchet, Ratchet', max_length=50),
        ),
        migrations.AddField(
            model_name='closure',
            name='units_per_case',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='closure',
            name='units_per_pallet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='closure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='closure',
            name='warehouse_inventory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productextended',
            name='label_size',
            field=models.CharField(blank=True, help_text='Can be derived from Bottle', max_length=50),
        ),
        migrations.AlterField(
            model_name='closure',
            name='name',
            field=models.CharField(help_text='Closure Name - primary identifier', max_length=200),
        ),
        migrations.AlterField(
            model_name='productextended',
            name='closure',
            field=models.ForeignKey(blank=True, help_text='Links to ClosureDatabase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='forecast_app.closure'),
        ),
        migrations.AlterField(
            model_name='productextended',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='forecast_app.formula'),
        ),
        migrations.AddIndex(
            model_name='closure',
            index=models.Index(fields=['user', 'name'], name='closures_user_id_8b852d_idx'),
        ),
        migrations.AddIndex(
            model_name='closure',
            index=models.Index(fields=['user', 'is_active'], name='closures_user_id_036fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='closure',
            index=models.Index(fields=['cap_size'], name='closures_cap_siz_0ac4e7_idx'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productextended',
            name='bottle',
            field=models.ForeignKey(blank=True, help_text='Links to BottleDatabase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='forecast_app.bottle'),
        ),
        migrations.AddIndex(
            model_name='productextended',
            index=models.Index(fields=['bottle'], name='products_ex_bottle__c76cca_idx'),
        ),
        migrations.AddIndex(
            model_name='productextended',
            index=models.Index(fields=['closure'], name='products_ex_closure_6ef144_idx'),
        ),
        migrations.AddIndex(
            model_name='productextended',
            index=models.Index(fields=['formula'], name='products_ex_formula_a0e3d6_idx'),
        ),
        migrations.AddIndex(
            model_name='bottle',
            index=models.Index(fields=['user', 'name'], name='bottles_user_id_2783b1_idx'),
        ),
        migrations.AddIndex(
            model_name='bottle',
            index=models.Index(fields=['user', 'is_active'], name='bottles_user_id_408dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='bottle',
            index=models.Index(fields=['size_oz'], name='bottles_size_oz_51a88a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bottle',
            unique_together={('user', 'name')},
        ),
    ]
