# Generated by Django 5.0.1 on 2026-03-12 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0005_bottle_alter_closure_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bottle',
            index=models.Index(fields=['user', 'is_active', 'name'], name='bottles_user_id_ce0fff_idx'),
        ),
        migrations.AddIndex(
            model_name='bottle',
            index=models.Index(fields=['supplier'], name='bottles_supplie_95d8ba_idx'),
        ),
        migrations.AddIndex(
            model_name='bottle',
            index=models.Index(fields=['shape'], name='bottles_shape_e07875_idx'),
        ),
        migrations.AddIndex(
            model_name='bottle',
            index=models.Index(fields=['warehouse_inventory'], name='bottles_warehou_0eb285_idx'),
        ),
        migrations.AddIndex(
            model_name='closure',
            index=models.Index(fields=['user', 'is_active', 'name'], name='closures_user_id_6c5443_idx'),
        ),
        migrations.AddIndex(
            model_name='closure',
            index=models.Index(fields=['category'], name='closures_categor_473b63_idx'),
        ),
        migrations.AddIndex(
            model_name='closure',
            index=models.Index(fields=['supplier'], name='closures_supplie_bb96f8_idx'),
        ),
        migrations.AddIndex(
            model_name='closure',
            index=models.Index(fields=['warehouse_inventory'], name='closures_warehou_7cf1ab_idx'),
        ),
    ]
