# Generated by Django 5.0.1 on 2026-03-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0006_bottle_bottles_user_id_ce0fff_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='allocated_inventory',
            field=models.IntegerField(blank=True, default=0, help_text='Inventory allocated to shipments', null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='max_warehouse_inventory',
            field=models.IntegerField(blank=True, help_text='Maximum storage capacity', null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='supplier_inventory',
            field=models.IntegerField(blank=True, help_text='Inbound inventory (ordered but not arrived)', null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='warehouse_inventory',
            field=models.IntegerField(blank=True, help_text='Available inventory in warehouse', null=True),
        ),
    ]
