# Generated by Django 5.2 on 2026-02-19 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecast_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fba_available', models.IntegerField(default=0)),
                ('fba_reserved', models.IntegerField(default=0)),
                ('fba_inbound', models.IntegerField(default=0)),
                ('awd_available', models.IntegerField(default=0)),
                ('awd_reserved', models.IntegerField(default=0)),
                ('awd_inbound', models.IntegerField(default=0)),
                ('age_0_to_90', models.IntegerField(default=0)),
                ('age_91_to_180', models.IntegerField(default=0)),
                ('age_181_to_270', models.IntegerField(default=0)),
                ('age_271_to_365', models.IntegerField(default=0)),
                ('age_365_plus', models.IntegerField(default=0)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_inventory', to='forecast_app.product')),
            ],
            options={
                'db_table': 'current_inventory',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('amazon_shipment_id', models.CharField(blank=True, max_length=100)),
                ('amazon_reference_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('shipment_type', models.CharField(choices=[('fba', 'FBA'), ('awd', 'AWD')], default='fba', max_length=10)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('ready', 'Ready to Ship'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('receiving', 'Receiving'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('ship_from_name', models.CharField(blank=True, max_length=200)),
                ('ship_from_address', models.TextField(blank=True)),
                ('destination_center', models.CharField(blank=True, max_length=100)),
                ('planned_ship_date', models.DateField(blank=True, null=True)),
                ('actual_ship_date', models.DateField(blank=True, null=True)),
                ('estimated_arrival', models.DateField(blank=True, null=True)),
                ('actual_arrival', models.DateField(blank=True, null=True)),
                ('total_units', models.IntegerField(default=0)),
                ('received_units', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField()),
                ('fba_available', models.IntegerField(default=0)),
                ('fba_reserved', models.IntegerField(default=0)),
                ('fba_inbound', models.IntegerField(default=0)),
                ('fba_inbound_receiving', models.IntegerField(default=0)),
                ('fba_inbound_shipped', models.IntegerField(default=0)),
                ('awd_available', models.IntegerField(default=0)),
                ('awd_reserved', models.IntegerField(default=0)),
                ('awd_inbound', models.IntegerField(default=0)),
                ('age_0_to_90', models.IntegerField(default=0)),
                ('age_91_to_180', models.IntegerField(default=0)),
                ('age_181_to_270', models.IntegerField(default=0)),
                ('age_271_to_365', models.IntegerField(default=0)),
                ('age_365_plus', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='forecast_app.product')),
            ],
            options={
                'db_table': 'inventory_snapshots',
                'get_latest_by': 'snapshot_date',
                'indexes': [models.Index(fields=['product', 'snapshot_date'], name='inventory_s_product_4e3cac_idx'), models.Index(fields=['snapshot_date'], name='inventory_s_snapsho_c3bf17_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_planned', models.IntegerField(default=0)),
                ('quantity_shipped', models.IntegerField(default=0)),
                ('quantity_received', models.IntegerField(default=0)),
                ('recommended_quantity', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='forecast_app.product')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory_app.shipment')),
            ],
            options={
                'db_table': 'shipment_items',
                'unique_together': {('shipment', 'product')},
            },
        ),
    ]
