# Generated by Django 5.0.1 on 2026-02-23 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0002_add_product_indexes'),
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=500)),
                ('reorder_quantity', models.IntegerField(default=2000)),
                ('notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label_inventory', to='forecast_app.product')),
            ],
            options={
                'verbose_name_plural': 'Label Inventories',
                'db_table': 'label_inventory',
                'ordering': ['-quantity'],
            },
        ),
    ]
