# Generated by Django 5.0.1 on 2026-02-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_labelinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentinventory',
            name='awd_outbound_to_fba',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentinventory',
            name='days_of_supply',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='currentinventory',
            name='fba_inbound_receiving',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentinventory',
            name='fba_inbound_shipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentinventory',
            name='fba_inbound_working',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentinventory',
            name='fba_reserved_customer_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentinventory',
            name='fba_reserved_fc_processing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentinventory',
            name='fba_reserved_fc_transfer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentinventory',
            name='fba_unfulfillable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='awd_outbound_to_fba',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='days_of_supply',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='fba_inbound_working',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='fba_reserved_customer_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='fba_reserved_fc_processing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='fba_reserved_fc_transfer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='fba_unfulfillable',
            field=models.IntegerField(default=0),
        ),
    ]
