# Generated by Django 5.0.1 on 2026-02-25 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_integration', '0001_initial'),
        ('inventory_app', '0003_add_inventory_detail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='amazon_account',
            field=models.ForeignKey(blank=True, help_text='The Amazon seller account this shipment belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='amazon_integration.amazonselleraccount'),
        ),
    ]
