# Generated by Django 6.0.2 on 2026-02-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_shipment_amazon_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(choices=[('fba', 'FBA'), ('awd', 'AWD'), ('mfg', 'Manufacturing Order'), ('hazmat', 'Hazmat')], default='fba', max_length=10),
        ),
    ]
