# Generated by Django 5.2 on 2026-02-19 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecast_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalityCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('weekly_indexes', models.JSONField(default=list)),
                ('monthly_indexes', models.JSONField(default=list)),
                ('data_source', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonality_curves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seasonality_curves',
            },
        ),
        migrations.CreateModel(
            name='VineClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateField()),
                ('units_claimed', models.IntegerField(default=1)),
                ('review_received', models.BooleanField(default=False)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('review_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vine_claims', to='forecast_app.product')),
            ],
            options={
                'db_table': 'vine_claims',
                'ordering': ['-claim_date'],
            },
        ),
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('units_sold', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orders', models.IntegerField(default=0)),
                ('sessions', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='forecast_app.product')),
            ],
            options={
                'db_table': 'daily_sales',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['product', 'date'], name='daily_sales_product_f1041c_idx'), models.Index(fields=['date'], name='daily_sales_date_34eaa5_idx')],
                'unique_together': {('product', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_order_id', models.CharField(db_index=True, max_length=50)),
                ('purchase_date', models.DateTimeField()),
                ('units', models.IntegerField(default=1)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fulfillment_channel', models.CharField(blank=True, max_length=20)),
                ('order_status', models.CharField(blank=True, max_length=50)),
                ('customer_state', models.CharField(blank=True, max_length=50)),
                ('customer_country', models.CharField(default='US', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='forecast_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'indexes': [models.Index(fields=['user', 'purchase_date'], name='orders_user_id_148b84_idx'), models.Index(fields=['product', 'purchase_date'], name='orders_product_a02552_idx')],
            },
        ),
    ]
