# Generated by Django 5.0.1 on 2026-02-23 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0001_initial'),
        ('forecast_app', '0002_add_product_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_ending', models.DateField()),
                ('units_sold', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orders', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_sales', to='forecast_app.product')),
            ],
            options={
                'db_table': 'weekly_sales',
                'ordering': ['-week_ending'],
                'indexes': [models.Index(fields=['product', 'week_ending'], name='weekly_sale_product_dc5b20_idx'), models.Index(fields=['week_ending'], name='weekly_sale_week_en_27cd42_idx'), models.Index(fields=['product', '-week_ending'], name='weekly_sale_product_e4814c_idx')],
                'unique_together': {('product', 'week_ending')},
            },
        ),
    ]
