# Generated by Django 5.0.1 on 2026-02-23 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0002_weeklysales'),
        ('forecast_app', '0002_add_product_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSeasonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_of_year', models.IntegerField()),
                ('search_volume', models.FloatField(default=100)),
                ('sv_smooth_env', models.FloatField(default=100)),
                ('seasonality_index', models.FloatField(default=1.0)),
                ('seasonality_multiplier', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonality', to='forecast_app.product')),
            ],
            options={
                'db_table': 'product_seasonality',
                'ordering': ['week_of_year'],
                'indexes': [models.Index(fields=['product', 'week_of_year'], name='product_sea_product_1df806_idx')],
                'unique_together': {('product', 'week_of_year')},
            },
        ),
    ]
