# Generated by Django 6.0.2 on 2026-03-10 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0003_productseasonality'),
        ('forecast_app', '0004_product_amazon_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='To Do', max_length=50)),
                ('assignee', models.CharField(blank=True, max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('bullets', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_action_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='forecast_app.product')),
            ],
            options={
                'db_table': 'action_items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='action_item_status_fd33af_idx'), models.Index(fields=['category'], name='action_item_categor_f1a1f4_idx'), models.Index(fields=['assignee'], name='action_item_assigne_b05266_idx'), models.Index(fields=['due_date'], name='action_item_due_dat_5ab63a_idx')],
            },
        ),
    ]
