# Generated by Django 6.0.2 on 2026-03-06 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0003_productseasonality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_asin', models.CharField(blank=True, db_index=True, max_length=20)),
                ('product_name', models.CharField(max_length=500)),
                ('product_brand', models.CharField(blank=True, max_length=200)),
                ('product_size', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=500)),
                ('status', models.CharField(default='To Do', max_length=50)),
                ('assignee', models.CharField(blank=True, max_length=200)),
                ('assignee_initials', models.CharField(blank=True, max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_html', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_by_initials', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'action_items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='action_item_user_id_e6acaa_idx'), models.Index(fields=['user', 'category'], name='action_item_user_id_507f29_idx'), models.Index(fields=['user', '-due_date'], name='action_item_user_id_b9d267_idx')],
            },
        ),
    ]
