# Generated by Django 6.0.2 on 2026-03-11 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0003_productseasonality'),
        ('forecast_app', '0004_product_amazon_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('blocked', 'Blocked'), ('completed', 'Completed')], default='todo', max_length=20)),
                ('category', models.CharField(choices=[('inventory', 'Inventory'), ('price', 'Price'), ('ads', 'Ads'), ('pdp', 'PDP'), ('other', 'Other')], default='inventory', max_length=20)),
                ('category_sub_info', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('description_html', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('bullets', models.JSONField(blank=True, default=list)),
                ('assignee_name', models.CharField(blank=True, max_length=100)),
                ('assignee_initials', models.CharField(blank=True, max_length=8)),
                ('created_by_name', models.CharField(blank=True, max_length=100)),
                ('created_by_initials', models.CharField(blank=True, max_length=8)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='forecast_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'action_items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='action_item_user_id_e6acaa_idx'), models.Index(fields=['user', 'category'], name='action_item_user_id_507f29_idx'), models.Index(fields=['user', 'due_date'], name='action_item_user_id_f9d040_idx'), models.Index(fields=['user', 'created_at'], name='action_item_user_id_8efaf9_idx')],
            },
        ),
    ]
