# Generated by Django 6.0.2 on 2026-03-10 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0003_productseasonality'),
        ('forecast_app', '0004_product_amazon_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('product_asin', models.CharField(blank=True, max_length=50)),
                ('product_brand', models.CharField(blank=True, max_length=255)),
                ('product_size', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In progress', 'In progress'), ('In review', 'In review'), ('Completed', 'Completed')], default='To Do', max_length=32)),
                ('category', models.CharField(blank=True, choices=[('Ads', 'Ads'), ('Inventory', 'Inventory'), ('PDP', 'PDP'), ('Price', 'Price')], max_length=32)),
                ('subject', models.CharField(max_length=255)),
                ('description_html', models.TextField(blank=True)),
                ('assignee_name', models.CharField(blank=True, max_length=255)),
                ('assignee_initials', models.CharField(blank=True, max_length=32)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='forecast_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'action_items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='action_item_user_id_e6acaa_idx'), models.Index(fields=['user', 'category'], name='action_item_user_id_507f29_idx'), models.Index(fields=['user', 'assignee_name'], name='action_item_user_id_3a4194_idx'), models.Index(fields=['user', 'due_date'], name='action_item_user_id_f9d040_idx')],
            },
        ),
    ]
