# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0004_actionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='category_sub_info',
            field=models.CharField(blank=True, max_length=100, default=''),
            preserve_default=False,
        ),
    ]
