# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0005_actionitem_category_sub_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='created_by_name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
