# Generated by Django 5.0.1 on 2026-02-25 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonSellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(db_index=True, max_length=100)),
                ('marketplace_id', models.CharField(choices=[('ATVPDKIKX0DER', 'United States'), ('A2EUQ1WTGCTBG2', 'Canada'), ('A1AM78C64UM0Y8', 'Mexico'), ('A1RKKUPIHCS9HS', 'Spain'), ('A1F83G8C2ARO7P', 'United Kingdom'), ('A13V1IB3VIYZZH', 'France'), ('A1805IZSGTT6HS', 'Netherlands'), ('A1PA6795UKMFR9', 'Germany'), ('APJ6JRA9NG5V4', 'Italy'), ('A2Q3Y263D00KWC', 'Brazil'), ('A1VC38T7YXB528', 'Japan'), ('AAHKV2X7AFYLW', 'China'), ('A39IBJ37TRP1C6', 'Australia'), ('A21TJRUUN4KGV', 'India'), ('A19VAU5U5O7RUS', 'Singapore'), ('A2VIGQ35RCS4UG', 'United Arab Emirates'), ('A1C3SOZRARQ6R3', 'Poland'), ('ARBP9OOSHTCHU', 'Egypt'), ('A33AVAJ2PDY3EV', 'Turkey'), ('A17E79C6D8DWNP', 'Saudi Arabia'), ('A2NODRKZP88ZB9', 'Sweden'), ('AJO27BESJ8LKQ', 'Belgium')], max_length=50)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('refresh_token_encrypted', models.BinaryField()),
                ('access_token_encrypted', models.BinaryField(blank=True, null=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'amazon_seller_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=64, unique=True)),
                ('marketplace_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'amazon_oauth_states',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('products', 'Product Sync'), ('inventory', 'Inventory Sync'), ('orders', 'Orders Sync'), ('full', 'Full Sync')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('amazon_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='amazon_integration.amazonselleraccount')),
            ],
            options={
                'db_table': 'amazon_sync_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='amazonselleraccount',
            index=models.Index(fields=['user', 'is_active'], name='amazon_sell_user_id_be9f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='amazonselleraccount',
            index=models.Index(fields=['seller_id', 'marketplace_id'], name='amazon_sell_seller__3017eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='amazonselleraccount',
            unique_together={('user', 'seller_id', 'marketplace_id')},
        ),
        migrations.AddIndex(
            model_name='oauthstate',
            index=models.Index(fields=['state', 'used'], name='amazon_oaut_state_bb0a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthstate',
            index=models.Index(fields=['expires_at'], name='amazon_oaut_expires_2495ba_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['amazon_account', 'operation', 'status'], name='amazon_sync_amazon__f764bb_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['started_at'], name='amazon_sync_started_07c2cc_idx'),
        ),
    ]
