# Generated by Django 5.0.1 on 2026-02-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonselleraccount',
            name='sync_current_step',
            field=models.CharField(choices=[('idle', 'Idle'), ('products', 'Syncing Products'), ('inventory', 'Syncing Inventory'), ('sales', 'Syncing Sales'), ('images', 'Loading Images')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='amazonselleraccount',
            name='sync_images_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amazonselleraccount',
            name='sync_inventory_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amazonselleraccount',
            name='sync_products_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amazonselleraccount',
            name='sync_sales_done',
            field=models.BooleanField(default=False),
        ),
    ]
